### ISSUE TITLE
Auto start service

### ISSUE THREAD

**Issue by de-code** [elifesciences/reviewer-suggestions-formula#25]
The service currently doesn't auto-start after the VM is started.

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/peerscout-formula/blob/master/salt/peerscout/config/etc-init-peerscout-server.conf should be amended with this line:
https://github.com/elifesciences/lax-formula/blob/master/salt/lax/config/etc-init-uwsgi-lax.conf#L2
